/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/pages/**/*.{js,jsx}"
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb59d",
        "surface": "#fff8f6",
        "tertiary-fixed-dim": "#59d5fb",
        "on-tertiary-container": "#003744",
        "on-surface": "#261814",
        "tertiary-fixed": "#b5ebff",
        "surface-bright": "#fff8f6",
        "on-tertiary-fixed": "#001f28",
        "on-primary": "#ffffff",
        "primary": "#ab3500",
        "on-background": "#261814",
        "secondary-container": "#91f78e",
        "on-secondary": "#ffffff",
        "tertiary-container": "#00a7cb",
        "on-surface-variant": "#594139",
        "tertiary": "#00677e",
        "primary-container": "#ff6b35",
        "surface-variant": "#f7ddd5",
        "surface-tint": "#ab3500",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004e60",
        "surface-dim": "#eed5cd",
        "surface-container-high": "#fde3db",
        "on-secondary-container": "#00731e",
        "inverse-on-surface": "#ffede8",
        "surface-container": "#ffe9e3",
        "inverse-surface": "#3c2d28",
        "background": "#fff8f6",
        "secondary-fixed": "#94f990",
        "on-primary-fixed": "#390c00",
        "on-error": "#ffffff",
        "surface-container-highest": "#f7ddd5",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005313",
        "inverse-primary": "#ffb59d",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbd0",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#78dc77",
        "outline": "#8d7168",
        "secondary": "#006e1c",
        "on-secondary-fixed": "#002204",
        "on-primary-container": "#5f1900",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1ed",
        "outline-variant": "#e1bfb5",
        "on-primary-fixed-variant": "#832600",
        "brand-orange": '#FF6B35',
        'brand-red': '#75070C',
        'brand-green': '#4F6815',
      },
      fontFamily: {
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
        "h1": ["Plus Jakarta Sans"],
        "h2": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "h3": ["Plus Jakarta Sans"]
      },
      spacing: {
        "lg": "24px",
        "unit": "8px",
        "md": "16px",
        "gutter": "24px",
        "xl": "40px",
        "xs": "4px",
        "container-max": "1280px",
        "sm": "8px",
        "stack-lg": "40px",
        "margin-page": "24px"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontSize: {
        "h1": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "h2": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "h3": ["24px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-bold": ["14px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }],
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        pulseSlow: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.05)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-8px)' },
          '40%': { transform: 'translateX(8px)' },
          '60%': { transform: 'translateX(-8px)' },
          '80%': { transform: 'translateX(8px)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        breathe: {
          '0%, 100%': { opacity: '0.35', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(1.04)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'fade-in': 'fadeIn 0.4s ease-out forwards',
        'pulse-slow': 'pulseSlow 2s ease-in-out infinite',
        shimmer: 'shimmer 2s linear infinite',
        shake: 'shake 0.4s ease-in-out',
        marquee: 'marquee 25s linear infinite',
        breathe: 'breathe 6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
